### ISSUE TITLE
Error raised when running `zenml up`

### ISSUE THREAD

**Issue by Muhammed-Rashid-07** [zenml-io/zenml-projects#74]
Error: Running the ZenML server locally as a background process is not supported on Windows. Please use the `--blocking` flag to run the server in blocking mode, or run the server in a Docker container by setting `--docker` instead.

**Comment by strickvl** [comment]
Hi, thanks for the longer error. Were you able to solve this issue / move past it? The error contains one way forward for you.

**Comment by strickvl** [comment]
Closing this in favor of #75 as it seems to be the same issue duplicated.
